nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:5173','http://127.0.0.1:5173']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Accept']
        expose_headers: ['Link', 'Location', 'Content_Location']
        max_age: 3600
    paths:
        '^/api': ~
